version: '3.8'

services:
  app:
    build: .
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://21032471huy:app123@chat-app.5eyed.mongodb.net/computer_product?retryWrites=true&w=majority&appName=chat-app
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 