openapi: 3.0.0
info:
  title: Cart Service API
  version: 1.0.0
  description: API for managing shopping carts
servers:
  - url: http://localhost:4005
    description: Cart service

paths:
  /add/{userId}/{productId}/{quantity}:
    post:
      tags: [Cart]
      summary: Add item to cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Item added successfully
        400:
          description: Invalid input

  /update/{userId}/{productId}/{quantity}:
    put:
      tags: [Cart]
      summary: Update item quantity
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Quantity updated
        404:
          description: Cart/item not found

  /remove/{userId}/{productId}:
    delete:
      tags: [Cart]
      summary: Remove item from cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Item removed
        404:
          description: Cart/item not found

  /clear/{userId}:
    delete:
      tags: [Cart]
      summary: Clear entire cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Cart cleared
        404:
          description: Cart not found

  /check/{userId}:
    get:
      tags: [Cart]
      summary: Validate cart contents
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Cart status
        404:
          description: Cart not found

  /{userId}:
    get:
      tags: [Cart]
      summary: Get cart contents
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Cart contents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Cart not found

components:
  schemas:
    Cart:
      type: object
      properties:
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer