openapi: 3.0.0
info:
  title: Order Service API
  version: 1.0.0
  description: Order Management API

paths:
  /orders:
    get:
      tags:
        - Orders
      summary: Get user's orders
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: List of orders

  /orders/create:
    post:
      tags:
        - Orders
      summary: Create new order
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - shippingAddress
              properties:
                shippingAddress:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
      responses:
        201:
          description: Order created successfully 