services:
  auth-service:
    build: .
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGODB_URI=mongodb+srv://21032471huy:app123@chat-app.5eyed.mongodb.net/computer_product?retryWrites=true&w=majority&appName=chat-app
      - JWT_SECRET=CAM
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: