openapi: 3.0.0
info:
  title: Payment Service API
  version: 1.0.0
  description: Payment Processing API

paths:
  /payments/create:
    post:
      tags:
        - Payments
      summary: Create payment for order
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - amount
                - method
              properties:
                orderId:
                  type: string
                amount:
                  type: number
                method:
                  type: string
                  enum: [momo, vnpay, paypal]
      responses:
        200:
          description: Payment created successfully

  /payments/webhook:
    post:
      tags:
        - Payments
      summary: Handle payment gateway webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentId:
                  type: string
                status:
                  type: string
                transactionId:
                  type: string
      responses:
        200:
          description: Webhook processed successfully 