openapi: 3.0.0
info:
  title: Shipping Service API
  version: 1.0.0
  description: Shipping Management API

paths:
  /shipping/track/{trackingNumber}:
    get:
      tags:
        - Shipping
      summary: Track shipment
      parameters:
        - in: path
          name: trackingNumber
          required: true
          schema:
            type: string
      responses:
        200:
          description: Shipment tracking information

  /shipping/calculate:
    post:
      tags:
        - Shipping
      summary: Calculate shipping cost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - items
              properties:
                address:
                  type: object
                  properties:
                    city:
                      type: string
                    state:
                      type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      weight:
                        type: number
                      quantity:
                        type: integer
      responses:
        200:
          description: Shipping cost calculated 