openapi: 3.0.0
info:
  title: Review Service API
  version: 1.0.0
  description: Product Review Management API

paths:
  /reviews/add:
    post:
      tags:
        - Reviews
      summary: Add product review
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - productId
                - rating
              properties:
                productId:
                  type: string
                rating:
                  type: number
                  minimum: 1
                  maximum: 5
                comment:
                  type: string
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        201:
          description: Review added successfully

  /reviews/{productId}:
    get:
      tags:
        - Reviews
      summary: Get product reviews
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: List of reviews 